#!/bin/sh
CUR_PATH=`pwd`
LUA_PATH=$CUR_PATH/3rd/skynet/3rd/lua
export PATH=$LUA_PATH:$PATH
#luarocks install ./3rd/lunit/rockspecs/lunitx-0.8-0.rockspec
#cp -R /usr/local/share/lua/5.2 /usr/local/share/lua/5.3


